[package]
name = "cvtemp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.88.8"
clap = { version = "4.5.1", features = ["derive", "string"] }