name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install llvm opencv --no-progress
    - name: Build
      run: OPENCV_INCLUDE_PATHS="C:\tools\opencv\build\include" OPENCV_LINK_LIBS="opencv_world490" OPENCV_LINK_PATHS="C:\tools\opencv\build\x64\vc15\ib" cargo build --release --verbose
      shell: bash
    - name: Run tests
      run: cargo test --verbose
